package.json
yarn.lock

node-ipcのバージョン固定します。（CVE-2022-23812の脆弱性がないバージョンに固定）
もともと9.1.1だったので互換性のある9.2.1にしています。
https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/

fix: node-ipc version fixed for CVE-2022-23812

---

src/view/finding/Finding.vue
src/view/finding/Resource.vue

リソース名、データソース名検索でパラメータに記号が入っていた場合にうまく送信できないケースがあったのでエンコード処理を追加します

fix: encode param

---

.dockerignore
Dockerfile
codebuild/multi-arch/buildspec-image.yml
codebuild/release/buildspec-image.yml
hack/docker-build.sh
package.json
src/main.js
yarn.lock

DataDog RUM（Real-User-Monitoring）を導入します。
- 本番、STG環境のみRUM設定をします
- 本番、STGで同じRUMのID、トークンを使用します
- DataDogの画面上で環境ごとにフィルタすることができます
- 公式イメージビルド時にはRUMの設定は含みません
- DataDog RUMのブラウザSDKを使用します。詳細な設定は[公式ドキュメント](https://docs.datadoghq.com/ja/real_user_monitoring/installation/?tab=us) を参照してください
- 環境ごとでRUMを設定したりしなかったりしますが、RISKENのフロントエンドのビルドではvue-cliを使用してますのでVUE_APP変数を利用しています。詳細はvue-cliの[公式ドキュメント](https://cli.vuejs.org/guide/mode-and-env.html)を参照してください
- また、CodeBuildのbuildspecでGITHUB_USER, GITHUB_TOKENは不要になったので削除しました（OSS化のタイミングで不要になりました。削除漏れ）

add: datadog RUM setting

---

src/view/code/NewSettingDialog.vue

github settingのnameに1文字でも入力を入れるとdisabled,isReadOnlyのフラグが立って編集できなくなる問題を修正します。
他のデータソースと同様に、一度登録した後の編集は不可能にしています。

fix github_setting.name disabled flag

---

Dockerfile
src/component/widget/list/User.vue

ユーザ検索で、ユーザ数が多い場合やAPIが遅延した場合にリスト内のデータに不整合が生じるバグがあったので修正します。
- 非同期処理でリストを生成する処理をやめ、リスト生成が完了するまでLoading状態にします
- 複数のAPIを叩く処理がありますが、PromiseAllで並行実行することでパフォーマンス影響を緩和します

fix: user search

---

package.json
yarn.lock

CVE-2022-37601の対応で、loader-utilsのバージョンを2.0.3以上に指定します

fix: loader-utils version

---

src/i18n/message/en.js
src/i18n/message/ja.js
src/view/google/GCPDataSource.vue
vue.config.js

GCPデータソースにバージョン情報を追加しました。
旧バージョンの場合はアップグレードボタンで最新バージョンに更新できるようにしました

add: gcp cloudsploit upgrade btn

---

codebuild/multi-arch/buildspec-image.yml
src/component/AppDrawer.vue
src/component/AppToolbar.vue
src/i18n/message/en.js
src/i18n/message/ja.js
src/router/config.js

環境変数から静的なリンクを生成できるように修正します。
静的なリンクは、メニューとヘッダーに表示します。(フッターにも表示することを考えましたが、ヘッダが常に表示されているため冗長になるかと思い入れませんでした。)
環境変数は、mapのarrayで以下のように設定します。
```shell
VUE_APP_STATIC_LINK=[{"title":"sample","url":"https://example.com"},{"title":"document","url":"https://docs.security-hub.jp/"}]
```
メニューのサンプル
ヘッダのサンプル
メニューのタイトルをクリックすることで、新タブでurlを表示します。
アイコンは固定にしていますが、環境変数で設定させるように修正することも可能です。
アイコンを動的にする場合、以下のように修正します。
- メニューアイコンが指定されていない場合にのみ現在表示しているアイコンを表示する
- 現在メニューに表示されている内容をサブメニューにして、メニューには`リンク`などを表示してそれをクリックすることでリンク一覧を表示する
- アイコンを動的にした場合、リンクが開かれることが想定しづらくなる可能性があると考えたため

add static link

---

src/view/diagnosis/ApplicationScan.vue

アプリケーションスキャンの設定を削除でプロジェクトタグも削除するようにします

fix: untag project

---

src/mixin/index.js
src/view/aws/DataSource.vue
src/view/google/GCPDataSource.vue

AWSとGCPのステータス画面で、status_detailがある場合にはワーニングアイコンを表示するようにします。
（OKとErrorステータスのみ）

fix: datasource warning

---

src/mixin/api/alert.js
src/mixin/api/aws.js
src/mixin/api/code.js
src/mixin/api/diagnosis.js
src/mixin/api/finding.js
src/mixin/api/google.js
src/mixin/api/iam.js
src/mixin/api/project.js
src/mixin/index.js
src/view/Dashboard.vue
src/view/alert/Alert.vue
src/view/alert/Condition.vue
src/view/alert/Notification.vue
src/view/alert/Rule.vue
src/view/aws/DataSource.vue
src/view/code/NewSettingDialog.vue
src/view/finding/Finding.vue
src/view/finding/Setting.vue
src/view/google/GCP.vue
src/view/google/GCPDataSource.vue
src/view/iam/AccessToken.vue
src/view/iam/Policy.vue
src/view/iam/User.vue
src/view/iam/UserReservation.vue
src/view/osint/DataSource.vue
src/view/osint/OSINT.vue
src/view/report/Finding.vue

プロジェクトを選択していない場合に、リクエストパラメータ `project_id=undefind` になってしまうバグを修正します

fix: project_id=undefind bug

---

src/i18n/message/en.js
src/i18n/message/ja.js
src/view/alert/Condition.vue

通知キャッシュ時間というのが分かりづらい（内部実装の視点の表現）ため、通知の抑制期間というラベルに変更します（他のサービスで利用されている表現）

fix: notification throttle label

---

codebuild/multi-arch/buildspec-image.yml
codebuild/release/buildspec-image.yml

buildspecで指定するnodejsのruntime versionをrevertします

revert buildspec

---

src/axios/index.js
src/view/Dashboard.vue
src/view/finding/Finding.vue

- ダッシュボードの重いAPIリクエストを修正します
- APIリクエストのタイムアウト時間を20秒まで緩和します
- Finding検索フィールドをみなします（アラート経由での画面遷移が多いのでよく使われる項目を上部に表示されるようにします）

Fix performance

---

src/component/AppToolbar.vue

プロジェクトボタンが右下よりになっていたので中央寄せに修正します。
before
after

adjust: pj btn position

---

src/component/widget/chart/LineChart.vue
src/component/widget/chart/PieChart.vue
src/component/widget/statistic/ReportNumberStatistic.vue
src/i18n/message/en.js
src/i18n/message/ja.js
src/view/report/Finding.vue

report画面の表示を修正します
以下が画面イメージです
カテゴリ、スコアをいじることでグラフとダウンロードするcsvの検索条件が変更されます。
(期間の変更はレポートのダウンロードと折れ線グラフにのみ影響)
追加したボタンからダウンロードする形式を選択して、ファイルをDLできます

fix report

---

src/view/aws/DataSource.vue

以下の修正を行います。
- aws datasourceのアップグレードボタンの崩れ
- AWSアカウント選択部分に[object Object]が表示される
- v-modelのデフォルト値に、selectボタンに表示するテキストのキーがなかったことが原因

fix  aws datasource

---

src/view/aws/DataSource.vue
src/view/osint/DataSource.vue

AWS
- セレクトメニューが[object Object]になる問題が修正しきれていなかったため対応します
- データソースを選択した際にeditDialogが出るタイミングでobjectになっていたものを修正
OSINT
- AWS,GCPなどと同様にステータスがOKかつdetailが存在する場合にアラートアイコンを出します

fix datasource

---

src/view/analysis/AttackFlow.vue

アタックフローのパブリックチェックボックスのON・OFFでリソース再検索をかけるようにします

fix: handle isPublic check

---

src/view/iam/Policy.vue
src/view/iam/Role.vue
src/view/iam/User.vue

page更新時にAPIで情報を取得するv-data-tableの表示がおかしかったため修正します
v-data-table-serverを使用するように変更(Findingなどと同じ形式)
プロジェクト単位で、多すぎるデータ量になることが想定されないため、逐次APIを叩く形式をやめます
画面のロード時、検索時に一括でデータを取得するように変更

fix datatable

---

src/mixin/api/alert.js
src/mixin/index.js

未ログイン時、プロジェクトが選択されていない時、別のプロジェクトが既に選択されている場合にも正しく登録が行えるようにストレージの値でなくパスパラメータのプロジェクトIDを使用するように変更します

fix update alert first viewed

---

src/router/index.js

localstorageに保存されているproject_idが存在しない（undefinedな）場合に、何も表示されないバグがありました。
たとえば初めてRISKENにアクセスしたユーザが何も表示されなくなる問題があります。

fix: router bug

---

src/i18n/message/en.js
src/i18n/message/ja.js
src/mixin/api/finding.js
src/view/finding/Finding.vue

pend findingに誤検知かどうかのFBを受けるためのチェックボックスを追加します
coreやDBでは、reasonとしてENUMで受けますが現状では誤検知以外の判定がないためチェックボックスにしてます
今後、用途が増えるタイミングでセレクトボックスにしたりするのもありかなと思います

add false positive to pending finding

---

src/view/code/GitHub.vue
src/view/code/SettingDialog.vue

CodeScan設定にたどり着けないバグを修正します。
また、一覧の項目が多く、右端のアクションが横スクロールしないとみれなくなっているため更新日時を非表示にします

fix: codescan setting

---

src/view/finding/Finding.vue

false positiveの✅が一度押して再度開き直すと✅済みになってしまうので、修正します

fix: default false positive flg

---

.env.sample
src/main.js
src/view/finding/Finding.vue

生成AIの表示は評価が高いのでデフォルトにしたいと思います。
APIトークンを設定していない場合には、Unsupportedという表示になります。

fix: default ai enabled

---

src/mixin/api/alert.js
src/mixin/index.js
src/view/alert/Alert.vue
src/view/finding/Finding.vue

プロジェクトに属するユーザーがFinding,Alert画面を閲覧した時にのみFirstAlertViewedAtを更新するように修正します
新規にRISKEN画面を開いた際にはuser_idを一時的に取得できないタイミングがあるため、以下の挙動にしました
- ロード済みで画面遷移時
ListUserを行った後、取得した結果にstoreから取得したuser_idが存在するか確認
存在する場合、FirstAlertViewedAtを更新
- ロード済みでなく、画面を開いた際(リンクから直接Alert、Finding画面に飛んだ場合など)
画面ロード時のsigninUserが完了するのを待つため、3秒待つ
その後、ListUserを実施し、取得した結果にstoreから取得したuser_idが存在するか確認
存在する場合、FirstAlertViewedAtを更新
AppToolbar.vueでのマウント時の処理に、[ await this.signinUser()](https://github.com/ca-risken/web/blob/master/src/component/AppToolbar.vue#L302)が存在する
この関数内で、一旦storeのuserを削除しsignin、getUserを実行後に取得し直したuserをstoreに格納する
この処理の間、storeのuserが存在しない状態となりuser_idが取得できない

Fix first alert firstviewed

---

src/view/finding/Finding.vue

Archive,PendされたFindingを再度更新する際に登録済みのデータがフォームに反映されない問題の修正
loadItem時のfindingごとのpendされたデータの持ち方を変更し、pendDialogを開く前に登録済みデータをフォームで使用するモデルに設定されるようにしました
また、登録されているデータにexpired_atが設定されている場合にはフォームにその日付が入るようになっています。そのため、日付の文字列が入った状態でPendボタンを押した際には日付をunixtimestampに変換する処理を追加しました。
複数のFindingをまとめてArchive,Pendする際には既存のデータが反映されるようにはしていません。

preserves the state of pend finding

---

src/i18n/message/en.js
src/i18n/message/ja.js
src/view/finding/Finding.vue

findingの詳細モーダルにて、Pendしたユーザーの名前を表示するように修正します(空の場合表示なし)
また、フォーマットを整えるためにcols、classの値を修正
PendFindingのExpiredAtが空の時にチップを表示しないようにしました
=> 元々空の場合や0値の場合には表示しないようにしていたが、(おそらく)前回の変更で0値で表示されるようになってしまっていたため

display pend user name

---

src/view/finding/Finding.vue

レコメンドデータがないFindingの詳細をクリックするとJSエラーが発生する事象を確認したので、その修正です。

fix: recommend

---

src/axios/index.js
src/i18n/message/en.js
src/i18n/message/ja.js
src/mixin/api/alert.js
src/view/error/Deny.vue

403画面の権限申請のボタンですが、クエリパラメータのproject_idで申請を出すようにします。
今まではLocalStorageのプロジェクトを取ってくる実装になっていたので、ここが目的とずれてる実装になってそうでした。
また、初めてRISKENにアクセスする人はLocalStorageにプロジェクト情報をもってないので、project_idがブランクになります。

fix: no project user error

---

src/axios/index.js
src/i18n/message/en.js
src/i18n/message/ja.js
src/mixin/index.js
src/view/Dashboard.vue
src/view/Home.vue
src/view/alert/Alert.vue
src/view/error/Deny.vue
src/view/finding/Finding.vue

XSRF-TOKENのセッションが切れた場合でも403エラー画面に遷移しますが、そこを考慮してUXを少し変更します。
- エラー画面の文言とボタンの位置を入れ替え
- まず、セッションが切れた場合にホームに戻ることを推奨する
- 続いて、「初めてアクセスする場合」の取るべき行動を提示する
- RISKENに直リンクでアクセスされる以下の画面には、最初にreSign処理を追加
- Finding
- Alert

fix: resign

---

src/component/widget/chat/AI.vue

AIチャットの最小化ボタンを追加
- Findingを見ながらチャットするケースでチャットビューが邪魔になる
- ✗で閉じると現状はチャット履歴が吹っ飛ぶ
- 一旦、最小化ボタンで代替する

add: minimize btn

---

src/i18n/message/en.js
src/i18n/message/ja.js
src/mixin/api/iam.js
src/view/admin/User.vue

Gateway、Webの変更に関連してWebのUIを変更します。
https://github.com/ca-risken/core/pull/386
https://github.com/ca-risken/gateway/pull/182
- RoleListに関する機能の削除
- ダイアログの名前変更、機能変更など
観点はコメントに記載しています
UIイメージ
Admin Menu -> 管理者ユーザを開いた状態です

add: is admin

---

src/component/widget/chat/AI.vue

AIチャットに現在選択中のプロジェクト情報のコンテキストを追加します。
サーバ側でproject_idを使ったツール（Finding情報取得）を呼び出せるようにするためです。

add: project context to AI chat

---

.pre-commit-config.yaml
Makefile
README.md

pre-commitを追加します。make installで動くようになります。
動作確認済です。
```
❯ g cm -m "add: pre-commit" --amend
make fmt.................................................................Failed
- hook id: make-fmt
- files were modified by this hook
```

add: pre-commit

---

src/i18n/message/en.js
src/i18n/message/ja.js
src/view/alert/Notification.vue

`@severity`にメンション時に脆弱性重大度に応じたメンションが飛ぶ事を説明として追加。(以下画像)
- 実装概要
- slack app , webhook 両方に実装
- 英語では以下の文面になる。
- When you mention @severity, it will be mentioned according to the severity of the vulnerability. 
- `@`がvueで特殊文字として扱われるため、v-htmlを使用。

[add]severity mention explain

---

.github/workflows/build-pr-web.yml

WebのCodeBuildをGithub actionsで置き換えます。nodejsのインストールを必要とするため、coreやawsと共通化はしません。

feat: add GitHub Actions workflow for building and tagging Docker container on PR

---

src/component/dialog/finding/Detail.vue

pend_noteをを表示できるように修正します。ローカルで動作確認済みです。

feat: add Markdown component to FindingDetailDialog
