ca-risken/web

src/component/widget/tag/ProjectTag.vue
ProjectTagの最大文字長を64から512へ変更します
=> update project tag

package.json, yarn.lock
- vueのversionを2系の安定版の最新バージョンまであげます
- yarn auditで出ていた脆弱性のパッチバージョンに更新
- その他依存関係ライブラリもあわせて更新
=> upgrade: packages

.gitignore, codebuild/multi-arch/buildspec-image.yml
=> fix: .env file

package.json, yarn.lock
=> rm: webpack because unused package

src/main.js, src/mixin/api/finding.js, src/view/alert/Alert.vue, src/view/finding/Finding.vue
アラート画面からのFinding検索のUXを改善します。
- Alertに紐づくすべてのFindingを一括検索機能できるようにします
- Findingの検索条件にFindingIDを複数指定をサポートします
- Alertに紐づくIDリストで検索します
- 効果測定のためにRUMのカスタムアクション名を設定します
=> fix: alert to finding ux

src/i18n/message/en.js, src/i18n/message/ja.js, src/view/aws/DataSource.vue, src/view/code/NewSettingDialog.vue, src/view/diagnosis/ApplicationScan.vue, src/view/diagnosis/WPScan.vue, src/view/finding/Finding.vue, src/view/google/GCPDataSource.vue, src/view/osint/DataSource.vue
Finding検索の導線を追加します
- Findingタグを検索リンクにします
- 各種DataSource画面から、「スキャン結果を見る」ボタンを追加します
=> add: finding search route

package.json, src/store/index.js, src/view/finding/Finding.vue, yarn.lock
=> add: history

src/i18n/message/en.js, src/i18n/message/ja.js, src/mixin/api/code.js, src/view/code/NewSettingDialog.vue
=> support: gitleaks fullscan

src/view/finding/Finding.vue
tagがないfindingを選択するとCSVダウンロードできないバグを修正します
=> fix: csv dw

src/view/code/GitHub.vue, src/view/code/NewSettingDialog.vue
gitleaksのenterprise関連の箇所を削除します
=> deprecated: github enterprise

src/router/config.js
Documentページの静的リンクはデフォルトで表示するようにします
=> fix static link

codebuild/release/buildspec-image.yml
パブリックイメージの方に環境固有の変数 `VUE_APP_xxx` が入らないキレイな状態でビルドしなおすように修正します
=> fix: public image build flow

src/view/alert/Rule.vue
=> fix: placeholder

src/view/alert/Rule.vue
=> fix: alert rule score validation

src/view/finding/Resource.vue
=> Fix resource

src/view/diagnosis/Portscan.vue
portscan作成削除のタイミングでプロジェクトタグの処理を追加します。
また、データ削除時のバグ修正もあわせて対応。
=> fix: porscan tag

src/view/diagnosis/Portscan.vue
=> fix: portscan error message

src/i18n/message/en.js, src/i18n/message/ja.js, src/view/alert/Condition.vue
=> add: analyze alert

src/view/aws/DataSource.vue, src/view/google/GCPDataSource.vue
=> fix: wrap style

src/component/AppFab.vue
=> fix scroll

src/mixin/api/alert.js, src/view/iam/UserReservation.vue
gatewayでbindのエラーが出ていたリクエストを修正します
=> fix request param

src/i18n/message/en.js, src/i18n/message/ja.js, src/view/aws/DataSource.vue, src/view/google/GCPDataSource.vue
Setup Allにて、有効化するデータソースを選択可能にします
問題なければ、googleにも同様の修正を行います。
イメージ
=> fix aws datasource

package.json, src/main.js, yarn.lock
DataDog RUM clickmap機能をサポートします
https://docs.datadoghq.com/real_user_monitoring/heatmaps/#prerequisites
=> support datadog-rum clickmap

src/i18n/message/en.js, src/i18n/message/ja.js, src/view/alert/Alert.vue
=> fix: action name

src/view/report/Finding.vue
- パフォーマンスの問題でデフォルトの開始日を設定します（古いプロジェクトはデータが多くなり、タイムアウトが発生してしまう可能性がある）
- 変数名のnowやyesterdayが実際の日付と異なっていたので、latestとlastDayに修正しました
=> fix: report

src/mixin/api/project.js, src/view/project/New.vue
プロジェクト名の重複チェックを追加します（この手のエラーが多いため）
=> add: project name validation

src/view/aws/DataSource.vue, src/view/google/GCPDataSource.vue
AWSのデータソースバージョンをサポートします
また、一覧表示項目が増えてしまったため少し調整しています。（GCPと足並みを揃えたいので並び順なども調整）
=> support: aws version

codebuild/multi-arch/buildspec-image.yml, codebuild/release/buildspec-image.yml
node jsのruntime versionを12 -> 16へ更新します
=> fix buildspec runtime version

codebuild/multi-arch/buildspec-batch.yml, codebuild/multi-arch/buildspec-image.yml, codebuild/release/buildspec-batch.yml, codebuild/release/buildspec-image.yml
codebuildのbuild,push時にlintを行わないように修正します。
また、その影響で不要となったinstall phaseを削除します。
合わせて、build imageのバージョンを更新します。
=> fix codebuild

src/component/widget/list/User.vue
gateway側でbindエラーが発生するため、緩和策としてフロントでバリデーションを追加します。
=> fix: user_id validation

src/view/alert/Condition.vue
=> fix: default alert throttle

src/i18n/message/en.js, src/i18n/message/ja.js, src/view/alert/Alert.vue, src/view/finding/Finding.vue
Findingのアクションメニューと選択された項目へのアクションにアーカイブを追加します。
処理としては、PENDINGの理由、期間を設定せずに無期限のPENDINGを行うだけです。
また、Alert詳細画面のチップ表示の修正を行いました。
=> Archive-finding

src/component/widget/chart/LineChart.vue, src/view/report/Finding.vue
=> fix line chart

src/component/widget/list/UserList.vue
ユーザー招待ダイアログのページングが正しく機能していなかったことの修正
=> fix user list

src/view/analysis/AttackFlow.vue
表示関連の細かなバグを修正します
- SERVICE_FILTERの指定がないサービスがうまく表示されないバグを修正
- http〜始まるリソース名はOSINT、Diagnosis関連のFindingが拾えるようにFinding検索時のフォーマットを調整
- アイコンがうまく表示されないバグを修正
=> fix: display bugs

src/mixin/api/datasource.js
アタックフロー分析のAPIがかなり時間がかかるケースがあるので、タイムアウトを少し伸ばします
=> fix: long axios

public/static/icon/question_answer_black_24dp.svg, src/i18n/message/en.js, src/i18n/message/ja.js, src/mixin/index.js, src/view/analysis/AttackFlow.vue, src/view/finding/Finding.vue, src/view/finding/Resource.vue
Finding, Resource画面からAttackFlow画面への導線を追加します。
AttackFlow画面では初期表示時にリクエストパラメータを受け取って条件が揃っていたらAttackFlow分析のAPIコールを実行します。
=> add: attack flow link

src/view/analysis/AttackFlow.vue
attack-flowの検索画面にpublicフィルターを追加します
=> add: public filter

src/view/finding/Finding.vue
ChatGPTのダイアログがうまく改行されてなかったので修正
=> fix: chatgpt format

src/mixin/index.js, src/view/analysis/AttackFlow.vue
=> add attackflow sns

src/view/finding/Finding.vue
検索履歴チップのデザイン調整します（チップの余白をつけたりしてます）
=> Fix history

src/view/admin/User.vue
adminのUser一覧画面のページングが正しく動作していない問題を修正します
=> Fix admin user

src/i18n/message/ja.js
ChatGPTに何を聞くのかの目的が不明なので文言を変更したいです
=> fix: japanese btn

src/mixin/api/alert.js, src/mixin/index.js, src/view/alert/Alert.vue, src/view/alert/Condition.vue, src/view/finding/Finding.vue
通知メッセージのリンクをクリックしてのAlert,Findingへのアクセスがあった際に、AlertのFirstViewedAtを更新する処理を追加します
=> update alert from slack

src/view/iam/User.vue
テーブルに表示するuserReservedの取得方法がおかしかったので修正します
=> fix display items

src/view/finding/Finding.vue
=> fix: search condition

Dockerfile, Makefile, nginx.conf, src/router/index.js
Vue のHTML5 Historyモードに切り替えたい
https://v3.router.vuejs.org/ja/guide/essentials/history-mode.html
- LB側でOIDC認証を前提としているアーキテクチャでは未ログインユーザの場合、パスやクエリパラメータがログイン後に欠落してしまう（#ハッシュ値はサーバに送信されないため）
- Historyモードに切り替えることでこの課題を解決したい
- 課題としてURLリンクを直接生成・記述している場合は修正が必要になる
- サーバでURLを直接生成しているケース
- ドキュメントなどにURLの直リンクを記載しているケース
- 他にある？
=> fix routing

src/view/osint/DataSource.vue
=> fix invoke scan

src/i18n/message/en.js, src/i18n/message/ja.js, src/mixin/index.js, src/view/finding/Finding.vue
PENDというタブ名はアーカイブという名前に変更します
（PEND＝期限付きのアーカイブ、という意味にしたのでタブの名称もアーカイブに統一しておきたい）
=> fix: pend tab name

src/i18n/message/en.js, src/i18n/message/ja.js, src/view/admin/User.vue, src/view/alert/Condition.vue, src/view/alert/Notification.vue, src/view/alert/Rule.vue, src/view/aws/AWS.vue, src/view/code/SettingDialog.vue, src/view/diagnosis/ApplicationScan.vue, src/view/diagnosis/Portscan.vue, src/view/diagnosis/WPScan.vue, src/view/finding/Setting.vue, src/view/google/GCP.vue, src/view/iam/User.vue, src/view/osint/OSINT.vue, src/view/project/Setting.vue
編集ダイアログのボタン名を `EDIT` → `SAVE`に変更します
=> fix: btn name

src/mixin/index.js
Alert画面、Finding画面を閲覧した際に該当プロジェクトのAlert閲覧時刻を更新するように変更
=> fix update alert first viewed

src/i18n/message/en.js, src/i18n/message/ja.js, src/view/alert/Notification.vue
=> support: slack app

src/view/finding/Finding.vue
=> fix: scc recommend

src/view/finding/Finding.vue
ペンディングダイアログで無期限を選択したらボタンのラベルをアーカイブに変更する
=> fix: change pend/archive label

src/component/AppToolbar.vue, src/mixin/api/iam.js, src/mixin/api/signin.js, src/mixin/index.js, src/view/Dashboard.vue, src/view/iam/Profile.vue
=> add: signout

src/view/azure/DataSource.vue
InvokeScan時に呼び出すfunction名が誤っていたのを修正します
=> fix invokeScan func

src/i18n/message/en.js, src/i18n/message/ja.js, src/mixin/index.js, src/view/finding/Finding.vue
Finding画面のデータソース検索の一覧とPoplular SearchにAzureを追加します
=> fix finding for azure

src/view/finding/Finding.vue
Findingのデータ中にあるURLリストを抽出して表示するようにします
=> add: URL lists

src/component/dialog/finding/Detail.vue, src/component/dialog/finding/Triage.vue, src/i18n/message/en.js, src/i18n/message/ja.js
スコアをクリックした時にトリアージdialogを表示するようにします
=> add: triage dialog

src/component/dialog/finding/Detail.vue, src/component/dialog/finding/Pend.vue, src/component/text/AIPanel.vue
- アーカイブNoteの表示が長いと切れていたり、リンク表示されない問題を改善
- 文字入力時の↑↓キーで次のアイテムにカーソル移動してしまう現象を修正
=> fix: archive view

src/component/dialog/finding/Pend.vue
=> fix: pend dialog

src/component/dialog/DeleteDialog.vue, src/view/iam/Policy.vue, src/view/iam/Role.vue
以下のダイアログをコンポーネント化します。RoleとPolicy.vueに適用しています。
ローカルで削除とキャンセルが成功するのを確認済み
=> add: delete dialog

src/component/widget/toolbar/PageHeader.vue, src/view/iam/Policy.vue, src/view/iam/Role.vue, src/view/iam/User.vue
=> add: page header

src/component/AppToolbar.vue
=> add: fix icon

src/i18n/message/en.js, src/i18n/message/ja.js, src/view/iam/Policy.vue, src/view/iam/Role.vue, src/view/iam/User.vue, src/view/organization/OrganizationInvitation.vue, src/view/organization/ProjectInvitation.vue, src/view/organization/Setting.vue, src/view/project/Setting.vue
こちらのレビューに従って一部修正しました。バグの修正も含んでいます。
https://github.com/ca-risken/web/pull/390
ローカルでの動作確認済。
=> add: refactor and i18n

src/component/widget/toolbar/PageHeader.vue, src/i18n/message/en.js, src/i18n/message/ja.js, src/view/organization/ProjectInvitation.vue
レビューに従い、Visit Projectとアイコンのキレを解決します
=> add: project visit

src/component/AppDrawer.vue, src/mixin/api/organization_iam.js, src/router/config.js, src/view/iam/User.vue, src/view/iam/UserReservation.vue
WebにOrganization用のユーザー予約を追加します。
動作確認をし、Delete、Put、Listのどれもが成功することを確認済みです。
=> add: user reserved

src/view/organization/ProjectInvitation.vue
こちらに対処するためにWeb画面を改修します
https://github.com/ca-risken/internal-community/issues/869
ローカルでの動作確認済み
=> fix: handle list project

package.json, yarn.lock
axiosのバージョンをアップデートします。間接依存するform-dataの修正のためです。
https://github.com/axios/axios/releases/tag/v0.30.1
マイナーバージョン間の更新なので問題ないかとは思いますが、ローカルでFinding画面やダッシュボードが開けることを確認済みです。
以下を実行しました
yarn upgrade axios@v0.30.1
=> fix: axios version
